# only works with 
# jflex 1.5.1 installed in the system and 
# the Java extension of yacc: 
# byacc/j from http://troi.lincom-asg.com/~rjamison/byacc/

JFLEX  = /usr/bin/jflex 
BYACCJ = yacc -J
JAVAC  = javac
JAVA   = java

#todo: add a target for building the jar file
# targets:

all: Parser.class

run: Parser.class
	$(JAVA) Parser

build: clean Parser.class

clean:
	rm -f *~ *.class *.java

Parser.class: Yylex.java Parser.java
	$(JAVAC) Parser.java

#build the lexer using jflex
EntrezASNLexer.java: calc.flex
	$(JFLEX) calc.flex

#build the parser using byaccj
EntrezASNParser: calc.y
	$(BYACCJ) calc.y
