import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintStream;

import junit.framework.TestCase;
import de.oliverpelz.*;

/**
 * This is an integration test.
 * 
 * The class Yylex is generated by JFLex from
 * <code>src/main/jflex/simple.flex</code>.
 * 
 * @author regis
 * 
 */
public class EntrezASNLexerPlaygroundTest extends TestCase {

	private static final String OUTPUT_FILE = "classes/resources/output-file1.asn.actual";

	/**
	 * Test that E parser behaves like expected.
	 * 
	 * @throws IOException
	 */
	public void testOutput() throws IOException {
		String[] argv = new String[1];
		argv[0] = "classes/resources/file1.asn";

		// the Yylex prints status on stdout
		File actual = new File(OUTPUT_FILE);  
		actual.delete();
		FileOutputStream fos = new FileOutputStream(OUTPUT_FILE, true);
		System.setOut(new PrintStream(fos));

		EntrezASNLexerPlayground.main(argv);
		
		fos.close();
		
		// test actual is expected
		File expected = new File("classes/resources/expected-file1.asn.good");
		assertTrue(expected.isFile());
		assertTrue(actual.isFile());

		BufferedReader actualContent = new BufferedReader(
				new FileReader(actual));
		BufferedReader expectedContent = new BufferedReader(new FileReader(
				expected));

		for (int lineNumber = 1;lineNumber!=-1; lineNumber++) {
			String expectedLine = expectedContent.readLine();
			String actualLine = actualContent.readLine();			
			assertEquals("Line "+lineNumber, expectedLine, actualLine);
			if (expectedLine==null) lineNumber=-2; //EOF
		}
	}
}
